version: '3.7'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fortune
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  composedb:
    build:
      context: ./composedb
    ports:
      - 7007:7007
    environment:
      GET_QUERY_PORT: 8000
      ADMIN_DIDS: did:key:z6Mkjs4ehQbTczpBKykv1jtJcxaFmyt2Ssd6wmT4K3xjcmAD
      DB_PATH: /root/.ceramic/indexing.sqlite
      DB_TABLE_GITHUB: kjzl6hvfrbw6c6iga46b1xj80g1a7m9p7y51qlw4yqyvtudk1yzbfprprcvfuhk
      DB_TABLE_FIVERR: kjzl6hvfrbw6c9vg1q5mo65vojdd131ezuakjrunhgca5qk0ty62s9ui3hqjz2z
      DB_TABLE_PLATFORM_RATING: kjzl6hvfrbw6cb02b8ypubp8ckvov8e9cn5hw80c8tdbxtbt9a0z59ky0eqb335
    volumes:
      - ./composedb/app:/usr/src/app

  credential-input:
    build:
      context: ./credential-input
    ports:
      - 3002:3000
    environment:
      REACT_APP_GITHUB_AUTH_URL: https://github.com/login/oauth/authorize?client_id=f9d6e5ff6997e5ead4f5
      REACT_APP_BACKEND_BASE_URL: http://localhost:3007
    command: [ "yarn", "start-prod" ]

  credential-oracle:
    build:
      context: ./credential-oracle
    # platform: linux/amd64
    ports:
      - 3007:8080
    environment:
      PORT: 8080
      GITHUB_CLIENT_SECRET: caef35b5e3ce3331605377835bd0fb27973e8454
      GITHUB_CLIENT_ID: f9d6e5ff6997e5ead4f5
      GITHUB_ACCESS_TOKEN_URL: https://github.com/login/oauth/access_token
      DID_PRIVATE_KEY: 59e83c249b8947d1524a3f5f66326c78759c86d75573027e7bef571c3fddfb90
      GITHUB_USER_MODEL_STREAM_ID: kjzl6hvfrbw6c5no55wlukc496fea0iujswirvarqnode65vmh5fjb2w926sqph
      CERAMIC_NODE_URL: http://composedb:7007
      CERAMIC_QUERY_URL: http://composedb:8000
      COMPOSITE_FILE_NAME: github_user_composite.json
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fortune
    command: [ "yarn", "start" ]

volumes:
  postgres-data:
